import { readdir, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import sharp from "sharp";

const PUBLIC_IMAGES = join(process.cwd(), "public", "images");
const OUTPUT = join(process.cwd(), "src", "lib", "image-blur.ts");

const exts = new Set([".jpg", ".jpeg", ".png", ".webp"]);

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (exts.has(entry.name.slice(entry.name.lastIndexOf(".")).toLowerCase())) {
      files.push(full);
    }
  }
  return files;
}

async function toBlur(file) {
  const buffer = await sharp(file)
    .resize(20, 20, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  const files = await walk(PUBLIC_IMAGES);
  const map = {};

  for (const file of files) {
    const rel = "/" + relative(join(process.cwd(), "public"), file).split(sep).join("/");
    map[rel] = await toBlur(file);
  }

  const sorted = Object.keys(map).sort();
  const body = sorted
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])},`)
    .join("\n");

  const ts = `// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Run \`npm run blur\` after adding or replacing images.

export const imageBlur: Record<string, string> = {
${body}
};

export function getBlur(src: string): string | undefined {
  return imageBlur[src];
}
`;

  await writeFile(OUTPUT, ts, "utf8");
  console.log(`Generated ${sorted.length} blur placeholders -> ${relative(process.cwd(), OUTPUT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
